import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/ui/navbar/Navbar";
import Footer from "@/ui/footer/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased pt-24`} 
      >
            <Navbar />
            <div className="lg:p-4 min-h-[140vh] flex flex-col ">{children}</div>
            <Footer />
      </body>
    </html>
  );
}
